apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: xe1rd3qjx-go-gitops
  description: This is GitOps manifest for xe1rd3qjx-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=xe1rd3qjx-go
    backstage.io/kubernetes-id: xe1rd3qjx-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: xe1rd3qjx-go
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:xe1rd3qjx-go
