apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: xe1rd3qjx-go
  janus-idp.io/tekton: xe1rd3qjx-go
  backstage.io/kubernetes-id: xe1rd3qjx-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: xe1rd3qjx-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
