apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: xe1rd3qjx-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: xe1rd3qjx-go 
  name: xe1rd3qjx-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: xe1rd3qjx-go 
